services:
  postgres:
    image: postgres:16-alpine
    container_name: itam-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: it_asset_db
      POSTGRES_USER: itasset
      POSTGRES_PASSWORD: itasset123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
